server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri: https://github.com/WilliamQuannigton/orderingsystem.git #git仓库地址
          searchPaths: config #仓库路径
          username: wangqian #git仓库用户名
          password: wangqian666,./ #git仓库密码
          force-pull: true #强制拉取更新
      label: master #仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/